### ISSUE TITLE
Missed rounding in message top-left corner

### ISSUE THREAD

**Issue by z2sx** [anticrm/sandbox#1]
Is this "as designed"?

<img width="579" alt="Screen Shot 2020-12-01 at 12 11 43 PM" src="https://user-images.githubusercontent.com/57532613/100733442-79857100-33ce-11eb-89ce-0baa08223a94.png">

**Comment by am35a** [comment]
yes
![image](https://user-images.githubusercontent.com/17111965/100736963-9462e000-33e4-11eb-8e5a-d7fce7d4b65d.png)

**Comment by z2sx** [comment]
@am35a thanks :) @alexeyenko are you sure we want to go such radically asymmetrical way? :)
